# Generated by Django 5.1.2 on 2024-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Budget', models.CharField(max_length=250)),
                ('Expenses', models.CharField(max_length=250)),
                ('Invoices', models.CharField(max_length=250)),
                ('Payments', models.CharField(max_length=250)),
                ('Taxes', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Quantity', models.CharField(max_length=250)),
                ('Availability', models.CharField(max_length=250)),
                ('Usage_History', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=250)),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250)),
                ('UserEmail', models.EmailField(max_length=250)),
                ('UserPassword', models.CharField(max_length=150)),
                ('UserPhone', models.CharField(max_length=20)),
                ('UserRole', models.CharField(max_length=100)),
            ],
        ),
    ]
