# Generated by Django 5.1.2 on 2024-10-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_project_manager_alter_project_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial',
            old_name='Budget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='Expenses',
            new_name='expenses',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='Invoices',
            new_name='invoices',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='Payments',
            new_name='payments',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='Taxes',
            new_name='taxes',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ItemName',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='Availability',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='Usage_History',
            new_name='usage_history',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskName',
            new_name='taskname',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
    ]
