# Generated by Django 5.1.2 on 2024-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=250)),
                ('ClientEmail', models.EmailField(max_length=250)),
                ('ClientPhonenamber', models.CharField(max_length=20)),
            ],
        ),
    ]
