# Generated by Django 5.1.2 on 2024-10-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_clientemail_client_clientemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientEmail',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientName',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientPhonenamber',
            new_name='client_phonenamber',
        ),
    ]
